name: Snowflake with Terraform 
on: 
   workflow_dispatch:
jobs:
  snowflake-with-terraform: 
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name : install terraform
        run: | 
           sudo apt-get install unzip
           if ! terraform -v terraform >/dev/null 2>&1; then
           wget https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
           #wget https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
           unzip terraform_1.0.11_linux_amd64.zip
           sudo mv terraform /usr/local/bin/
           else echo "Terraform is already installed"
           terraform --version 
           fi
           echo "Terraform build started.."
                 
      - name: Set permissions of directory
        run : |
          echo "=====================List all the files of main folder============================"
          cd $GITHUB_WORKSPACE
          ls
          sudo chmod -R 777 $GITHUB_WORKSPACE  ###Modifying permissions to make the dir executable
          cd $GITHUB_WORKSPACE
    
      - name: Terraform init
        run: |
            cd $GITHUB_WORKSPACE
            terraform init
            
      - name: Terraform validate
        run: 
            export TF_VAR_account=${{ secrets.Account }}
            export TF_VAR_password=${{ secrets.Password }}
            terraform validate
            
      - name: Terraform plan
        run: |
            cd $GITHUB_WORKSPACE
            export TF_VAR_account=${{ secrets.Account }}
            export TF_VAR_password=${{ secrets.Password }}
            terraform plan
            ls -a
        
