# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

#   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name : install terraform
        run: | 
           sudo apt-get install unzip
           if ! terraform -v terraform >/dev/null 2>&1; then
           wget https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
           unzip terraform_1.0.11_linux_amd64.zip
           sudo mv terraform /usr/local/bin/
           else echo "Terraform is already installed"
           terraform --version 
           fi
           echo "Terraform build started.."
           
      - name: Create a Directory
        run: mkdir GITHUB_PATH/terraform
        
      - name: Move files to base directory
        run : |
          echo "=====================List all the files of main folder============================"
          cd $GITHUB_WORKSPACE
          ls
          #### Copy file to src directory and correct file permissions
          echo "=================== COPY src Files to the Build environment ======================"
          sudo rm -rf GITHUB_PATH/terraform
          sudo mkdir  GITHUB_PATH/terraform 
          sudo cp -v -r * GITHUB_PATH/terraform  
          ### copy all the files to the build environment
          echo "list all the files in GITHUB_PATH/terraform" && ls
          sudo chmod -R 777 GITHUB_PATH/terraform  ###Modifying permissions to make the dir executable
          cdGITHUB_PATH/terraform
          echo "list all the files in Deployments Directory" && ls
      
      - name: Terraform init
        run: |
            sudo cd  GITHUB_PATH/terraform
            terraform init
            
      - name: Terraform plan
        run: |
            sudo cd  GITHUB_PATH/terraform
            terraform plan
        
